services:
  hbnu-api:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: hbnu-api
    ports:
      - "3000:3000"
    environment:
      - NODE_ENV=production
      - PORT=3000
      - LOG_LEVEL=info
    volumes:
      - ./logs:/app/logs
    restart: unless-stopped
    networks:
      - hbnu-network

networks:
  hbnu-network:
    driver: bridge
