services:
  hbnu-api:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: hbnu-api
    ports:
      - "3000:3000"
    environment:
      - NODE_ENV=production
      - PORT=3000
      - LOG_LEVEL=info
      - REDIS_HOST=redis
      - REDIS_PORT=6379
      - REDIS_PASSWORD=${REDIS_PASSWORD:-RedisDefaultProductionPass123!}
      - TZ=Asia/Seoul
    volumes:
      - ./logs:/app/logs
      - /etc/localtime:/etc/localtime:ro
    restart: unless-stopped
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:3000/health"]
      interval: 300s
      timeout: 10s
      retries: 3
      start_period: 40s
    networks:
      - hbnu-network
    depends_on:
      - redis

  redis:
    image: redis:7-alpine
    container_name: hbnu-redis
    command: redis-server --appendonly yes --requirepass ${REDIS_PASSWORD:-RedisDefaultProductionPass123!}
    environment:
      - TZ=Asia/Seoul
    volumes:
      - redis-data:/data
      - /etc/localtime:/etc/localtime:ro
    networks:
      - hbnu-network
    healthcheck:
      test: ["CMD", "redis-cli", "-a", "${REDIS_PASSWORD:-RedisDefaultProductionPass123!}", "ping"]
      interval: 10s
      timeout: 5s
      retries: 3
    restart: unless-stopped

networks:
  hbnu-network:
    driver: bridge

volumes:
  redis-data:
    driver: local
