export const INSTITUTION_ENUM = {
  HANBAT: 'HANBAT',
  KANGWON: 'KANGWON',
  KNU: 'KNU',
  GNU: 'GNU',
  GINUE: 'GINUE',
  GJUE: 'GJUE',
  GNUE: 'GNUE',
  GWNU: 'GWNU',
  GKNU: 'GKNU',
  KONGJU: 'KONGJU',
  KUNSAN: 'KUNSAN',
  KUMOH: 'KUMOH',
  MOKPO: 'MOKPO',
  MMU: 'MMU',
  PKNU: 'PKNU',
  SCNU: 'SCNU',
  CHANGWON: 'CHANGWON',
  UT: 'UT',
  KNOU: 'KNOU',
  KMOU: 'KMOU',
  DNUE: 'DNUE',
  BNUE: 'BNUE',
  PNU: 'PNU',
  SEOULTECH: 'SEOULTECH',
  SNUE: 'SNUE',
  JNU: 'JNU',
  JBNU: 'JBNU',
  JNUE: 'JNUE',
  JEJUNU: 'JEJUNU',
  CUE: 'CUE',
  CJE: 'CJE',
  CNUE: 'CNUE',
  CNU: 'CNU',
  CBNU: 'CBNU',
  HKNU: 'HKNU',
  KNUE: 'KNUE',
  KNSU: 'KNSU',
  SNU: 'SNU',
  INU: 'INU',
} as const;

export type InstitutionType =
  (typeof INSTITUTION_ENUM)[keyof typeof INSTITUTION_ENUM];
