import {
  INSTITUTION_SERVICE_TYPE_ENUM,
  InstitutionServiceType,
} from './institution-service-type.enum';

export const INSTITUTION_OPPORTUNITY_SERVICE_TYPES: InstitutionServiceType[] = [
  INSTITUTION_SERVICE_TYPE_ENUM.SCHOLARSHIP,
  INSTITUTION_SERVICE_TYPE_ENUM.CAREER_PROGRAM,
  INSTITUTION_SERVICE_TYPE_ENUM.JOB_FAIR,
  INSTITUTION_SERVICE_TYPE_ENUM.FIELD_PRACTICE,
  INSTITUTION_SERVICE_TYPE_ENUM.INTERNSHIP,
  INSTITUTION_SERVICE_TYPE_ENUM.EXTRACURRICULAR,
  INSTITUTION_SERVICE_TYPE_ENUM.MENTORING,
  INSTITUTION_SERVICE_TYPE_ENUM.STARTUP,
  INSTITUTION_SERVICE_TYPE_ENUM.GLOBAL_PROGRAM,
];

export const INSTITUTION_OPPORTUNITY_DISCOVERY_MODES = {
  LIVE: 'live',
  CATALOG_FALLBACK: 'catalog_fallback',
} as const;

export type InstitutionOpportunityDiscoveryMode =
  (typeof INSTITUTION_OPPORTUNITY_DISCOVERY_MODES)[keyof typeof INSTITUTION_OPPORTUNITY_DISCOVERY_MODES];
